apiVersion: v1
kind: Service
metadata:
  name: camel-core-downstream-service
  labels:
    app: camel-core-downstream-service
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 9190
    targetPort: 9190
    protocol: TCP
  selector:
    app: camel-core-downstream-service
